### ISSUE TITLE
"The connection was reset" when navigating to localhost:8000 in browser

### ISSUE THREAD

**Issue by lbussell** [cs3451/f19-a0#2]
OS: macOS 10.14.6

When running `npm run serve` from the project folder, the terminal displays the following (as if everything is working fine):

```
[logan@mac: ~/.../cs3451/f12-a0-submit--lbussell]$ npm run serve

> a0@1.0.0 serve /.../cs3451/f12-a0-submit--lbussell
> PORT=8000 ./node_modules/https-localhost/index.js

Serving static path: /.../cs3451/f12-a0-submit--lbussell
Server running on port 8000.
```

However, when accessing `http://localhost:8000/` from Firefox, the browser says "The connection was reset". Chrome says "This page isn’t working. localhost didn’t send any data.".

I can run `python2 -m SimpleHTTPServer` and it serves the content just fine. Not sure what's wrong with https-localhost.

**Comment by blairmacintyre** [comment]
did you try https instead of http?  I don't think the https-localhost server opens a non-secure port.

**Comment by lbussell** [comment]
Yep, that's it. Could've sworn I tried that. Thanks for the help!
