### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by silvai** [cs3451/f19-a0#4]
Is there an easy way to debug without starting the server each time? I mostly want to just print out my variables.
Thanks!

**Comment by blairmacintyre** [comment]
You need a way to load things into the browser, so some sort of server is needed.

But you don’t need to run and stop it.  Just open a second shell window and run the server there.  You can recompile as needed in the first window, and reload the page.

**Comment by silvai** [comment]
Thanks! tsc --watch + knowing I didn't have to restart the server saved me a ton of time!!
